name: Dependabot Auto-Merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    uses: wcpos/.github/.github/workflows/dependabot-auto-merge.yml@73969eb81ae5e73f06512b07db0da853793e9b7e # main 2026-03-18
    secrets: inherit # required: callee workflow does not declare secret inputs
